//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchivumWpf.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchivumWpf.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVE FIELD LOANS.
        /// </summary>
        public static string Circ_ActiveLoansHeader {
            get {
                return ResourceManager.GetString("Circ_ActiveLoansHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input an RR Number above to assess the file for issuance or return..
        /// </summary>
        public static string Circ_AwaitingScanDesc {
            get {
                return ResourceManager.GetString("Circ_AwaitingScanDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWAITING DOSSIER SCAN.
        /// </summary>
        public static string Circ_AwaitingScanTitle {
            get {
                return ResourceManager.GetString("Circ_AwaitingScanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter designated borrower name / ID....
        /// </summary>
        public static string Circ_BorrowerWatermark {
            get {
                return ResourceManager.GetString("Circ_BorrowerWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assess Dossier.
        /// </summary>
        public static string Circ_BtnAssess {
            get {
                return ResourceManager.GetString("Circ_BtnAssess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize Issuance.
        /// </summary>
        public static string Circ_BtnAuthorizeIssue {
            get {
                return ResourceManager.GetString("Circ_BtnAuthorizeIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Record.
        /// </summary>
        public static string Circ_BtnCloseRecord {
            get {
                return ResourceManager.GetString("Circ_BtnCloseRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Return.
        /// </summary>
        public static string Circ_BtnProcessReturn {
            get {
                return ResourceManager.GetString("Circ_BtnProcessReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BORROWER.
        /// </summary>
        public static string Circ_ColBorrower {
            get {
                return ResourceManager.GetString("Circ_ColBorrower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE NAME.
        /// </summary>
        public static string Circ_ColFileName {
            get {
                return ResourceManager.GetString("Circ_ColFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISSUE DATE.
        /// </summary>
        public static string Circ_ColIssueDate {
            get {
                return ResourceManager.GetString("Circ_ColIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETURN DATE.
        /// </summary>
        public static string Circ_ColReturnDate {
            get {
                return ResourceManager.GetString("Circ_ColReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RR NUMBER.
        /// </summary>
        public static string Circ_ColRrNumber {
            get {
                return ResourceManager.GetString("Circ_ColRrNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECTOR.
        /// </summary>
        public static string Circ_ColSector {
            get {
                return ResourceManager.GetString("Circ_ColSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        public static string Circ_ColStatus {
            get {
                return ResourceManager.GetString("Circ_ColStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOSSIER INTELLIGENCE.
        /// </summary>
        public static string Circ_DossierIntel {
            get {
                return ResourceManager.GetString("Circ_DossierIntel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISSUE TO BORROWER.
        /// </summary>
        public static string Circ_IssueTitle {
            get {
                return ResourceManager.GetString("Circ_IssueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrower Name:.
        /// </summary>
        public static string Circ_LblBorrowerName {
            get {
                return ResourceManager.GetString("Circ_LblBorrowerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chronological Span:.
        /// </summary>
        public static string Circ_LblChronoSpan {
            get {
                return ResourceManager.GetString("Circ_LblChronoSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Status:.
        /// </summary>
        public static string Circ_LblCurrentStatus {
            get {
                return ResourceManager.GetString("Circ_LblCurrentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deck:.
        /// </summary>
        public static string Circ_LblDeck {
            get {
                return ResourceManager.GetString("Circ_LblDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type:.
        /// </summary>
        public static string Circ_LblFileType {
            get {
                return ResourceManager.GetString("Circ_LblFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date:.
        /// </summary>
        public static string Circ_LblIssueDate {
            get {
                return ResourceManager.GetString("Circ_LblIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages:.
        /// </summary>
        public static string Circ_LblPages {
            get {
                return ResourceManager.GetString("Circ_LblPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Location:.
        /// </summary>
        public static string Circ_LblPhysicalLocation {
            get {
                return ResourceManager.GetString("Circ_LblPhysicalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Date:.
        /// </summary>
        public static string Circ_LblReturnDate {
            get {
                return ResourceManager.GetString("Circ_LblReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RR Number:.
        /// </summary>
        public static string Circ_LblRrNumber {
            get {
                return ResourceManager.GetString("Circ_LblRrNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector:.
        /// </summary>
        public static string Circ_LblSector {
            get {
                return ResourceManager.GetString("Circ_LblSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf:.
        /// </summary>
        public static string Circ_LblShelf {
            get {
                return ResourceManager.GetString("Circ_LblShelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject / File Name:.
        /// </summary>
        public static string Circ_LblSubjectFileName {
            get {
                return ResourceManager.GetString("Circ_LblSubjectFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Name:.
        /// </summary>
        public static string Circ_LblSubjectName {
            get {
                return ResourceManager.GetString("Circ_LblSubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Number:.
        /// </summary>
        public static string Circ_LblSubjectNumber {
            get {
                return ResourceManager.GetString("Circ_LblSubjectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string Circ_LblTo {
            get {
                return ResourceManager.GetString("Circ_LblTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction ID:.
        /// </summary>
        public static string Circ_LblTransactionId {
            get {
                return ResourceManager.GetString("Circ_LblTransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter history by exact RR Number....
        /// </summary>
        public static string Circ_LedgerSearchWatermark {
            get {
                return ResourceManager.GetString("Circ_LedgerSearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process dossier requests, manage active loans, and returning dossiers..
        /// </summary>
        public static string Circ_MainDesc {
            get {
                return ResourceManager.GetString("Circ_MainDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier Circulation Administration.
        /// </summary>
        public static string Circ_MainTitle {
            get {
                return ResourceManager.GetString("Circ_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string Circ_NA {
            get {
                return ResourceManager.GetString("Circ_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Circ_None {
            get {
                return ResourceManager.GetString("Circ_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Return.
        /// </summary>
        public static string Circ_PendingReturn {
            get {
                return ResourceManager.GetString("Circ_PendingReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This dossier is currently active in the field. Confirm physical return to vault..
        /// </summary>
        public static string Circ_ReturnDesc {
            get {
                return ResourceManager.GetString("Circ_ReturnDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTHORIZE RETURN.
        /// </summary>
        public static string Circ_ReturnTitle {
            get {
                return ResourceManager.GetString("Circ_ReturnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target exact RR Number for circulation....
        /// </summary>
        public static string Circ_SearchWatermark {
            get {
                return ResourceManager.GetString("Circ_SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVE LOAN.
        /// </summary>
        public static string Circ_StatusActiveLoan {
            get {
                return ResourceManager.GetString("Circ_StatusActiveLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETURNED.
        /// </summary>
        public static string Circ_StatusReturned {
            get {
                return ResourceManager.GetString("Circ_StatusReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Field Loans.
        /// </summary>
        public static string Circ_TabActiveLoans {
            get {
                return ResourceManager.GetString("Circ_TabActiveLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circulation Desk.
        /// </summary>
        public static string Circ_TabDesk {
            get {
                return ResourceManager.GetString("Circ_TabDesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circulation Ledger.
        /// </summary>
        public static string Circ_TabLedger {
            get {
                return ResourceManager.GetString("Circ_TabLedger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total History Records:.
        /// </summary>
        public static string Circ_TotalHistoryRecords {
            get {
                return ResourceManager.GetString("Circ_TotalHistoryRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTHORIZE DISPOSAL.
        /// </summary>
        public static string Dis_AuthorizeDisposalTitle {
            get {
                return ResourceManager.GetString("Dis_AuthorizeDisposalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input a valid RR Number above to retrieve the file record for scheduling or permanent destruction..
        /// </summary>
        public static string Dis_AwaitingTargetDesc {
            get {
                return ResourceManager.GetString("Dis_AwaitingTargetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWAITING TARGET DOSSIER.
        /// </summary>
        public static string Dis_AwaitingTargetTitle {
            get {
                return ResourceManager.GetString("Dis_AwaitingTargetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Request.
        /// </summary>
        public static string Dis_BtnCancelRequest {
            get {
                return ResourceManager.GetString("Dis_BtnCancelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Dossier.
        /// </summary>
        public static string Dis_BtnCloseDossier {
            get {
                return ResourceManager.GetString("Dis_BtnCloseDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM DESTRUCTION.
        /// </summary>
        public static string Dis_BtnConfirmDestruction {
            get {
                return ResourceManager.GetString("Dis_BtnConfirmDestruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispose.
        /// </summary>
        public static string Dis_BtnDispose {
            get {
                return ResourceManager.GetString("Dis_BtnDispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXECUTE DISPOSAL.
        /// </summary>
        public static string Dis_BtnExecuteDisposal {
            get {
                return ResourceManager.GetString("Dis_BtnExecuteDisposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate Dossier.
        /// </summary>
        public static string Dis_BtnLocate {
            get {
                return ResourceManager.GetString("Dis_BtnLocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        public static string Dis_BtnRecover {
            get {
                return ResourceManager.GetString("Dis_BtnRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Queue Status.
        /// </summary>
        public static string Dis_BtnUpdateQueue {
            get {
                return ResourceManager.GetString("Dis_BtnUpdateQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIONS.
        /// </summary>
        public static string Dis_ColActions {
            get {
                return ResourceManager.GetString("Dis_ColActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTHORIZED BY.
        /// </summary>
        public static string Dis_ColAuthorizedBy {
            get {
                return ResourceManager.GetString("Dis_ColAuthorizedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE DISPOSED.
        /// </summary>
        public static string Dis_ColDateDisposed {
            get {
                return ResourceManager.GetString("Dis_ColDateDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE NAME.
        /// </summary>
        public static string Dis_ColFileName {
            get {
                return ResourceManager.GetString("Dis_ColFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REASON.
        /// </summary>
        public static string Dis_ColReason {
            get {
                return ResourceManager.GetString("Dis_ColReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RR NUMBER.
        /// </summary>
        public static string Dis_ColRrNumber {
            get {
                return ResourceManager.GetString("Dis_ColRrNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULED FOR.
        /// </summary>
        public static string Dis_ColScheduledFor {
            get {
                return ResourceManager.GetString("Dis_ColScheduledFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECTOR.
        /// </summary>
        public static string Dis_ColSector {
            get {
                return ResourceManager.GetString("Dis_ColSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth:.
        /// </summary>
        public static string Dis_LblAuthFormat {
            get {
                return ResourceManager.GetString("Dis_LblAuthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized By *.
        /// </summary>
        public static string Dis_LblAuthorizedBy {
            get {
                return ResourceManager.GetString("Dis_LblAuthorizedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposal Scheduled:.
        /// </summary>
        public static string Dis_LblDisposalScheduled {
            get {
                return ResourceManager.GetString("Dis_LblDisposalScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for Disposal *.
        /// </summary>
        public static string Dis_LblReasonForDisposal {
            get {
                return ResourceManager.GetString("Dis_LblReasonForDisposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason:.
        /// </summary>
        public static string Dis_LblReasonFormat {
            get {
                return ResourceManager.GetString("Dis_LblReasonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector:.
        /// </summary>
        public static string Dis_LblSector {
            get {
                return ResourceManager.GetString("Dis_LblSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string Dis_LblStatus {
            get {
                return ResourceManager.GetString("Dis_LblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target File:.
        /// </summary>
        public static string Dis_LblTargetFileFormat {
            get {
                return ResourceManager.GetString("Dis_LblTargetFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To-Be-Removed Date.
        /// </summary>
        public static string Dis_LblToBeRemovedDate {
            get {
                return ResourceManager.GetString("Dis_LblToBeRemovedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule archival purges, execute permanent disposals, and review the destruction ledger..
        /// </summary>
        public static string Dis_MainDesc {
            get {
                return ResourceManager.GetString("Dis_MainDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier Retention &amp; Disposal Administration.
        /// </summary>
        public static string Dis_MainTitle {
            get {
                return ResourceManager.GetString("Dis_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instantly log this record in the destruction database. This action is irreversible..
        /// </summary>
        public static string Dis_PermanentDesc {
            get {
                return ResourceManager.GetString("Dis_PermanentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. PERMANENT DISPOSAL.
        /// </summary>
        public static string Dis_PermanentTitle {
            get {
                return ResourceManager.GetString("Dis_PermanentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERMANENTLY DISPOSED.
        /// </summary>
        public static string Dis_PermDisposedTitle {
            get {
                return ResourceManager.GetString("Dis_PermDisposedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a future date to flag this file for removal in system reports..
        /// </summary>
        public static string Dis_ScheduleDesc {
            get {
                return ResourceManager.GetString("Dis_ScheduleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. SCHEDULE DISPOSAL.
        /// </summary>
        public static string Dis_ScheduleTitle {
            get {
                return ResourceManager.GetString("Dis_ScheduleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target exact RR Number for disposal....
        /// </summary>
        public static string Dis_SearchWatermark {
            get {
                return ResourceManager.GetString("Dis_SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposed Log.
        /// </summary>
        public static string Dis_TabAudit {
            get {
                return ResourceManager.GetString("Dis_TabAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Be Removed Queue.
        /// </summary>
        public static string Dis_TabQueue {
            get {
                return ResourceManager.GetString("Dis_TabQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search &amp; Target.
        /// </summary>
        public static string Dis_TabSearch {
            get {
                return ResourceManager.GetString("Dis_TabSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New File Type.
        /// </summary>
        public static string Settings_AddFileType {
            get {
                return ResourceManager.GetString("Settings_AddFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Sector.
        /// </summary>
        public static string Settings_AddSector {
            get {
                return ResourceManager.GetString("Settings_AddSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        public static string Settings_Alpha {
            get {
                return ResourceManager.GetString("Settings_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Title.
        /// </summary>
        public static string Settings_AppTitle {
            get {
                return ResourceManager.GetString("Settings_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMATED SQL BACKUPS.
        /// </summary>
        public static string Settings_AutoBackups {
            get {
                return ResourceManager.GetString("Settings_AutoBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Destination Folder (Local or Cloud Sync).
        /// </summary>
        public static string Settings_BackupDest {
            get {
                return ResourceManager.GetString("Settings_BackupDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Settings_Blue {
            get {
                return ResourceManager.GetString("Settings_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add File Type.
        /// </summary>
        public static string Settings_BtnAddFileType {
            get {
                return ResourceManager.GetString("Settings_BtnAddFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add Sector.
        /// </summary>
        public static string Settings_BtnAddSector {
            get {
                return ResourceManager.GetString("Settings_BtnAddSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Selection.
        /// </summary>
        public static string Settings_CancelSelection {
            get {
                return ResourceManager.GetString("Settings_CancelSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Palette.
        /// </summary>
        public static string Settings_ColorPalette {
            get {
                return ResourceManager.GetString("Settings_ColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECTOR COLOR PICKER.
        /// </summary>
        public static string Settings_ColorPickerTitle {
            get {
                return ResourceManager.GetString("Settings_ColorPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Color Tag (Type Hex or Open Palette):.
        /// </summary>
        public static string Settings_ColorTag {
            get {
                return ResourceManager.GetString("Settings_ColorTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Color.
        /// </summary>
        public static string Settings_ConfirmColor {
            get {
                return ResourceManager.GetString("Settings_ConfirmColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current User.
        /// </summary>
        public static string Settings_CurrentUser {
            get {
                return ResourceManager.GetString("Settings_CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSTGRESQL CONNECTION.
        /// </summary>
        public static string Settings_DbConnection {
            get {
                return ResourceManager.GetString("Settings_DbConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Server (e.g., localhost).
        /// </summary>
        public static string Settings_DbHost {
            get {
                return ResourceManager.GetString("Settings_DbHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name.
        /// </summary>
        public static string Settings_DbName {
            get {
                return ResourceManager.GetString("Settings_DbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Settings_DbPassword {
            get {
                return ResourceManager.GetString("Settings_DbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Settings_DbUser {
            get {
                return ResourceManager.GetString("Settings_DbUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Export Directory.
        /// </summary>
        public static string Settings_DefExportDir {
            get {
                return ResourceManager.GetString("Settings_DefExportDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Pagination Size.
        /// </summary>
        public static string Settings_DefPageSize {
            get {
                return ResourceManager.GetString("Settings_DefPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Daily Automated SQL Database Backup.
        /// </summary>
        public static string Settings_EnableAutoBackup {
            get {
                return ResourceManager.GetString("Settings_EnableAutoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type (e.g., Confidential).
        /// </summary>
        public static string Settings_FileTypeHint {
            get {
                return ResourceManager.GetString("Settings_FileTypeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final ARGB Output Code.
        /// </summary>
        public static string Settings_FinalArgb {
            get {
                return ResourceManager.GetString("Settings_FinalArgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Settings_Green {
            get {
                return ResourceManager.GetString("Settings_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Hex Code.
        /// </summary>
        public static string Settings_HexHint {
            get {
                return ResourceManager.GetString("Settings_HexHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCALIZATION &amp; USER.
        /// </summary>
        public static string Settings_LocUser {
            get {
                return ResourceManager.GetString("Settings_LocUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage local parameters, database connections, and classification schemas..
        /// </summary>
        public static string Settings_MainDesc {
            get {
                return ResourceManager.GetString("Settings_MainDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings &amp; Configuration.
        /// </summary>
        public static string Settings_MainTitle {
            get {
                return ResourceManager.GetString("Settings_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE FILE TYPES.
        /// </summary>
        public static string Settings_ManageFileTypes {
            get {
                return ResourceManager.GetString("Settings_ManageFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE SECTORS.
        /// </summary>
        public static string Settings_ManageSectors {
            get {
                return ResourceManager.GetString("Settings_ManageSectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORGANIZATION DETAILS.
        /// </summary>
        public static string Settings_OrgDetails {
            get {
                return ResourceManager.GetString("Settings_OrgDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name.
        /// </summary>
        public static string Settings_OrgName {
            get {
                return ResourceManager.GetString("Settings_OrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Settings_Red {
            get {
                return ResourceManager.GetString("Settings_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Category Settings.
        /// </summary>
        public static string Settings_SaveCategory {
            get {
                return ResourceManager.GetString("Settings_SaveCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Database Settings.
        /// </summary>
        public static string Settings_SaveDatabase {
            get {
                return ResourceManager.GetString("Settings_SaveDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save General Settings.
        /// </summary>
        public static string Settings_SaveGeneral {
            get {
                return ResourceManager.GetString("Settings_SaveGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Name.
        /// </summary>
        public static string Settings_SectorNameHint {
            get {
                return ResourceManager.GetString("Settings_SectorNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM DEFAULTS.
        /// </summary>
        public static string Settings_SysDefaults {
            get {
                return ResourceManager.GetString("Settings_SysDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Language.
        /// </summary>
        public static string Settings_SysLanguage {
            get {
                return ResourceManager.GetString("Settings_SysLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database &amp; Backups.
        /// </summary>
        public static string Settings_TabDatabase {
            get {
                return ResourceManager.GetString("Settings_TabDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General &amp; Display.
        /// </summary>
        public static string Settings_TabGeneral {
            get {
                return ResourceManager.GetString("Settings_TabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vault Categories.
        /// </summary>
        public static string Settings_TabVault {
            get {
                return ResourceManager.GetString("Settings_TabVault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        public static string Settings_TestConnection {
            get {
                return ResourceManager.GetString("Settings_TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Theme.
        /// </summary>
        public static string Settings_UITheme {
            get {
                return ResourceManager.GetString("Settings_UITheme", resourceCulture);
            }
        }
    }
}
