//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchivumWpf.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchivumWpf.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New File Type.
        /// </summary>
        public static string Settings_AddFileType {
            get {
                return ResourceManager.GetString("Settings_AddFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Sector.
        /// </summary>
        public static string Settings_AddSector {
            get {
                return ResourceManager.GetString("Settings_AddSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        public static string Settings_Alpha {
            get {
                return ResourceManager.GetString("Settings_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Title.
        /// </summary>
        public static string Settings_AppTitle {
            get {
                return ResourceManager.GetString("Settings_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOMATED SQL BACKUPS.
        /// </summary>
        public static string Settings_AutoBackups {
            get {
                return ResourceManager.GetString("Settings_AutoBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Destination Folder (Local or Cloud Sync).
        /// </summary>
        public static string Settings_BackupDest {
            get {
                return ResourceManager.GetString("Settings_BackupDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Settings_Blue {
            get {
                return ResourceManager.GetString("Settings_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add File Type.
        /// </summary>
        public static string Settings_BtnAddFileType {
            get {
                return ResourceManager.GetString("Settings_BtnAddFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add Sector.
        /// </summary>
        public static string Settings_BtnAddSector {
            get {
                return ResourceManager.GetString("Settings_BtnAddSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Selection.
        /// </summary>
        public static string Settings_CancelSelection {
            get {
                return ResourceManager.GetString("Settings_CancelSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Palette.
        /// </summary>
        public static string Settings_ColorPalette {
            get {
                return ResourceManager.GetString("Settings_ColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECTOR COLOR PICKER.
        /// </summary>
        public static string Settings_ColorPickerTitle {
            get {
                return ResourceManager.GetString("Settings_ColorPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Color Tag (Type Hex or Open Palette):.
        /// </summary>
        public static string Settings_ColorTag {
            get {
                return ResourceManager.GetString("Settings_ColorTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Color.
        /// </summary>
        public static string Settings_ConfirmColor {
            get {
                return ResourceManager.GetString("Settings_ConfirmColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current User.
        /// </summary>
        public static string Settings_CurrentUser {
            get {
                return ResourceManager.GetString("Settings_CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSTGRESQL CONNECTION.
        /// </summary>
        public static string Settings_DbConnection {
            get {
                return ResourceManager.GetString("Settings_DbConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Server (e.g., localhost).
        /// </summary>
        public static string Settings_DbHost {
            get {
                return ResourceManager.GetString("Settings_DbHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name.
        /// </summary>
        public static string Settings_DbName {
            get {
                return ResourceManager.GetString("Settings_DbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Settings_DbPassword {
            get {
                return ResourceManager.GetString("Settings_DbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Settings_DbUser {
            get {
                return ResourceManager.GetString("Settings_DbUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Export Directory.
        /// </summary>
        public static string Settings_DefExportDir {
            get {
                return ResourceManager.GetString("Settings_DefExportDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Pagination Size.
        /// </summary>
        public static string Settings_DefPageSize {
            get {
                return ResourceManager.GetString("Settings_DefPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Daily Automated SQL Database Backup.
        /// </summary>
        public static string Settings_EnableAutoBackup {
            get {
                return ResourceManager.GetString("Settings_EnableAutoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type (e.g., Confidential).
        /// </summary>
        public static string Settings_FileTypeHint {
            get {
                return ResourceManager.GetString("Settings_FileTypeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final ARGB Output Code.
        /// </summary>
        public static string Settings_FinalArgb {
            get {
                return ResourceManager.GetString("Settings_FinalArgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Settings_Green {
            get {
                return ResourceManager.GetString("Settings_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Hex Code.
        /// </summary>
        public static string Settings_HexHint {
            get {
                return ResourceManager.GetString("Settings_HexHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCALIZATION &amp; USER.
        /// </summary>
        public static string Settings_LocUser {
            get {
                return ResourceManager.GetString("Settings_LocUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage local parameters, database connections, and classification schemas..
        /// </summary>
        public static string Settings_MainDesc {
            get {
                return ResourceManager.GetString("Settings_MainDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings &amp; Configuration.
        /// </summary>
        public static string Settings_MainTitle {
            get {
                return ResourceManager.GetString("Settings_MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE FILE TYPES.
        /// </summary>
        public static string Settings_ManageFileTypes {
            get {
                return ResourceManager.GetString("Settings_ManageFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE SECTORS.
        /// </summary>
        public static string Settings_ManageSectors {
            get {
                return ResourceManager.GetString("Settings_ManageSectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORGANIZATION DETAILS.
        /// </summary>
        public static string Settings_OrgDetails {
            get {
                return ResourceManager.GetString("Settings_OrgDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name.
        /// </summary>
        public static string Settings_OrgName {
            get {
                return ResourceManager.GetString("Settings_OrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Settings_Red {
            get {
                return ResourceManager.GetString("Settings_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Category Settings.
        /// </summary>
        public static string Settings_SaveCategory {
            get {
                return ResourceManager.GetString("Settings_SaveCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Database Settings.
        /// </summary>
        public static string Settings_SaveDatabase {
            get {
                return ResourceManager.GetString("Settings_SaveDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save General Settings.
        /// </summary>
        public static string Settings_SaveGeneral {
            get {
                return ResourceManager.GetString("Settings_SaveGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector Name.
        /// </summary>
        public static string Settings_SectorNameHint {
            get {
                return ResourceManager.GetString("Settings_SectorNameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM DEFAULTS.
        /// </summary>
        public static string Settings_SysDefaults {
            get {
                return ResourceManager.GetString("Settings_SysDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Language.
        /// </summary>
        public static string Settings_SysLanguage {
            get {
                return ResourceManager.GetString("Settings_SysLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database &amp; Backups.
        /// </summary>
        public static string Settings_TabDatabase {
            get {
                return ResourceManager.GetString("Settings_TabDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General &amp; Display.
        /// </summary>
        public static string Settings_TabGeneral {
            get {
                return ResourceManager.GetString("Settings_TabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vault Categories.
        /// </summary>
        public static string Settings_TabVault {
            get {
                return ResourceManager.GetString("Settings_TabVault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        public static string Settings_TestConnection {
            get {
                return ResourceManager.GetString("Settings_TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Theme.
        /// </summary>
        public static string Settings_UITheme {
            get {
                return ResourceManager.GetString("Settings_UITheme", resourceCulture);
            }
        }
    }
}
