// <auto-generated />
using System;
using ArchivumWpf.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArchivumWpf.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326035118_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArchivumWpf.Models.BorrowRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BorrowedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("borrowed_date");

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("borrower_name");

                    b.Property<string>("FileRrNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_rr_number");

                    b.Property<int>("FileSerialNumber")
                        .HasColumnType("integer")
                        .HasColumnName("file_serial_number");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_returned");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("returned_date");

                    b.HasKey("Id");

                    b.HasIndex("FileSerialNumber");

                    b.ToTable("borrow_records");
                });

            modelBuilder.Entity("ArchivumWpf.Models.EntryHistoryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RrNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubjectNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("entry_history_record");
                });

            modelBuilder.Entity("ArchivumWpf.Models.FileRecord", b =>
                {
                    b.Property<int>("SerialNumber")
                        .HasColumnType("integer")
                        .HasColumnName("serial_number");

                    b.Property<DateTime>("AddedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_status");

                    b.Property<int?>("DeckNumber")
                        .HasColumnType("integer")
                        .HasColumnName("deck_number");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<int?>("FileNumber")
                        .HasColumnType("integer")
                        .HasColumnName("file_number");

                    b.Property<string>("FileType")
                        .HasColumnType("text")
                        .HasColumnName("file_type");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_removed");

                    b.Property<DateTime?>("RemovedDate")
                        .HasColumnType("date")
                        .HasColumnName("removed_date");

                    b.Property<string>("RrNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rr_number");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sector");

                    b.Property<int?>("ShelfNumber")
                        .HasColumnType("integer")
                        .HasColumnName("shelf_number");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("SubjectNumber")
                        .HasColumnType("text")
                        .HasColumnName("subject_number");

                    b.Property<DateTime?>("ToBeRemovedDate")
                        .HasColumnType("date")
                        .HasColumnName("to_be_removed_date");

                    b.Property<int?>("TotalPages")
                        .HasColumnType("integer")
                        .HasColumnName("total_pages");

                    b.HasKey("SerialNumber");

                    b.HasIndex("RrNumber")
                        .IsUnique();

                    b.ToTable("file_records");
                });

            modelBuilder.Entity("ArchivumWpf.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("TotpSecret")
                        .HasColumnType("text")
                        .HasColumnName("totp_secret");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("ArchivumWpf.Models.BorrowRecord", b =>
                {
                    b.HasOne("ArchivumWpf.Models.FileRecord", "File")
                        .WithMany("BorrowHistory")
                        .HasForeignKey("FileSerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("ArchivumWpf.Models.FileRecord", b =>
                {
                    b.Navigation("BorrowHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
